export const UPLOAD_CONSTANTS = {
  MAX_FILE_SIZE: 10 * 1024 * 1024, // 10 MB
  ALLOWED_MIME_TYPES: [
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/avif',
    'image/svg+xml',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  ],
  ALLOWED_EXTENSIONS: [
    '.jpg',
    '.jpeg',
    '.png',
    '.webp',
    '.avif',
    '.svg',
    '.pdf',
    '.doc',
    '.docx',
  ],
  UPLOAD_FOLDERS: [
    'blogs',
    'blog-authors',
    'services',
    'portfolio',
    'careers',
    'resumes',
    'team',
    'testimonials',
    'seo',
    'logos',
    'documents',
    'contact',
    'settings',
    'favicon',
    'temp',
  ],
};
