export { default as ServicesLayout } from './ServicesLayout';
export { default as WebsiteDevelopment } from './WebsiteDevelopment';
export { default as ShopifyDevelopment } from './ShopifyDevelopment';
export { default as SEOOptimization } from './SEOOptimization';
export { default as EcommerceWebsite } from './EcommerceWebsite';
export { default as PPCServices } from './PPCServices';
export { default as AppDevelopment } from './AppDevelopment';
export { default as SoftwareDevelopment } from './SoftwareDevelopment';
export { default as DigitalMarketing } from './DigitalMarketing';
export { default as CustomSoftwareDevelopmentPage } from './CustomSoftwareDevelopmentPage';
export { default as AgencyPartnership } from './AgencyPartnership';
export { default as WhiteLabelDevelopment } from './WhiteLabelDevelopment';
export { default as WebsiteMaintenance } from './WebsiteMaintenance';
export { default as TechnicalSEO } from './TechnicalSEO';
export { default as SEOMaintenance } from './SEOMaintenance';
export { default as WebsiteSpeedOptimization } from './WebsiteSpeedOptimization';
export { default as AIAutomation } from './AIAutomation';
export * from './NewServices';
